apiVersion: v1
appVersion: 1.7.6
description: A Helm chart for Citrix API Gateway
home: https://www.citrix.com
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
maintainers:
- email: priyanka.sharma@citrix.com
  name: Priyanka Sharma
- email: subash.dangol@citrix.com
  name: Subash Dangal
name: citrix-k8s-ingress-controller
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
version: 1.7.6
