apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.helm.k8s.io/v1alpha1",
          "kind": "CitrixIngressController",
          "metadata": {
            "name": "cic"
          },
          "spec": {
            "cic": {
              "image": "registry.connect.redhat.com/citrix/citrix-ingress-controller:latest",
              "pullPolicy": "IfNotPresent"
            },
            "defaultSSLCert": null,
            "exporter": {
              "image": "registry.connect.redhat.com/citrix/citrix-adc-metrics-exporter:latest",
              "ports": {
                "containerPort": 8888
              },
              "pullPolicy": "IfNotPresent",
              "required": false
            },
            "ingressClass": null,
            "kubernetesURL": null,
            "license": {
              "accept": false
            },
            "logLevel": "DEBUG",
            "loginFileName": null,
            "nodeWatch": false,
            "nsIP": "x.x.x.x",
            "nsNamespace": null,
            "nsPort": 443,
            "nsProtocol": "HTTPS",
            "nsVIP": null,
            "openshift": true
          }
        }
      ]
    capabilities: Basic Install
    categories: Networking
    certified: "false"
    containerImage: registry.connect.redhat.com/citrix/citrix-k8s-ingress-controller:latest
    createdAt: "06-22-2020"
    description: "Citrix API GW is an enterprise-class solution that supports access control, rate limiting and analytics in one integrated system. It can be deployed on-prem, on a private cloud or deployed in a hybrid fashion where its components can be distributed and deployed across multiple cloud and on-prem infrastructures. Citrix API GW operator secures APIs and provides a management plane and control plane for managing and monitoring APIs. This operator can be used deploy Citrix Ingress Controller in an Openshift environment along with a few CRDs that will assist in API Gateway features."
    repository: https://github.com/citrix/citrix-k8s-ingress-controller
    support: Citrix Ingress Controller
  name: cic-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: CitrixIngressController
      name: citrixingresscontrollers.charts.helm.k8s.io
      version: v1alpha1
      displayName: Citrix API Gateway
      description: "Deploys Citrix Ingress Controller (CIC) in the cluster."
    - kind: authpolicy
      name: authpolicies.citrix.com
      version: v1beta1
      displayName: authpolicies
      description: "Authentication policies are used to enforce access restrictions to resources hosted by an application or an API server."
    - kind: HTTPRoute
      name: httproutes.citrix.com
      version: v1alpha1
      displayName: httproutes
      description: "Content Routing (CR) is the execution of defined rules that determine the placement and configuration of network traffic between users and web applications, based on the content being sent. For example, a pattern in the URL or header fields of the request."
    - kind: Listener
      name: listeners.citrix.com
      version: v1alpha1
      displayName: listeners
      description: "Content Routing (CR) is the execution of defined rules that determine the placement and configuration of network traffic between users and web applications, based on the content being sent. For example, a pattern in the URL or header fields of the request."
    - kind: ratelimit
      name: ratelimits.citrix.com
      version: v1beta1
      displayName: ratelimits
      description: "In a Kubernetes deployment, you can rate limit the requests to the resources on the back end server or services using rate limiting feature provided by the ingress Citrix ADC."
    - kind: vip
      name: vips.citrix.com
      version: v1
      displayName: vips
      description: "Citrix provides a CustomResourceDefinitions (CRD) called VIP for asynchronous communication between the IPAM controller and Citrix ingress controller. The IPAM controller is provided by Citrix for IP address management."
    - kind: rewritepolicy
      name: rewritepolicies.citrix.com
      version: v1
      displayName: rewritepolicies
      description: "In kubernetes environment, to deploy specific layer 7 policies to handle scenarios such as, redirecting HTTP traffic to a specific URL, blocking a set of IP addresses to mitigate DDoS attacks, imposing HTTP to HTTPS and so on, requires you to add appropriate libraries within the microservices and manually configure the policies. Instead, you can use the Rewrite and Responder features provided by the Ingress Citrix ADC device to deploy these policies."
  description: "Citrix API GW is an enterprise-class solution that supports access control, rate limiting and analytics in one integrated system. It can be deployed on-prem, on a private cloud or deployed in a hybrid fashion where its components can be distributed and deployed across multiple cloud and on-prem infrastructures.
Citrix API GW operator secures APIs and provides a management plane and control plane for managing and monitoring APIs.
This operator can be used deploy Citrix Ingress Controller in an Openshift environment along with a few CRDs that will assist in API Gateway features."
  displayName: Citrix API Gateway
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAgVBMVEUAAAD////8/PwEBAT5+fk8PDyzs7Pz8/PT09NLS0uFhYUICAilpaXl5eXw8PD29vbf39/Hx8fAwMBDQ0PZ2dmZmZliYmLNzc3BwcE1NTUnJydcXFytra11dXXp6emOjo5/f39ra2sVFRUuLi5SUlIgICBHR0eTk5MTExN6enpxcXFb0XjtAAAPlUlEQVR4nO1diZarKBBFNLtmT+wkdvb08v7/A4c9qIBKMOqcvjOnXxajXKsoiqIogfd/B2i6AbXjj2H38cew+/hj2H38MXQL6EH41gt6fzJ0DEj+87y3yvFPhm5wHH70kzD8/iQ4hWHSX8aR6kj34q2BoaSHwXqRnEcPoMF19dlfrAP6I/KzGgxRLQxxM2fR4nTo/aip+dLrn959vIgG9IedYIjbOOj/3n1Bxge+nyKlIHo/96eB1xEtnW+2tP0+pUf+VxAUH/EvR5u1+9a4Y8gG8/hb1+nK4RSTk0HozDtwwVC0ZR7uiGxUGlkau+85OSl0pLFOZEgMxGBxmQCme9YU6Q+3ywE3WK/DlZbONj3AO91LMqQa0NtMXRmdlxiK2xydpNY5wjjynJjW12QIYYDaMP/njpeMS0wu0RxD5kfPfyfq0cABPucv0nuNIR3bT4RfDQzpKcfHhhkmk9dtSwHCZhhCMkDEu/qIPfFYoAsG1h3SmiGaEp1rlZ2ES/TCtMOSIXKSl3tEcPIGfuguPvr2PpxtPzz+Asfjn57hBN3Hy9F2bKzKkF3mA89q67CgSor4z0/fcvyvxhDS/hCcahsBDSw/Z1a+alWG+L/oDt6loU+G6GpfcxsxWmjpApmYybvMqMwQ/Cwt9LQ6wxDU5MQUMCRKc6qTIesDNXnZZbGtPPRXkCGmOD00SxCAkTLM6oYhQrRqmqAPehXDVZUYRtd3m1AVxcewHoZI++Mf8G4TmiHHUEmKZRniUaI5blnErhkS6/UxaVpBn/A/HDPEIlw0qqBpIGOwcMsQyXCOB913zJVKAd3r0uamiCGbl62vTZPKYV5y6C+UYYBZHntN88njOi/nhpeQIWI5apqOCqNyYbhCGWKKhxZZGQlbNwwRxk1T0eHihCH0+k0TUQNrVVhiSlzcD4etGSMywBRLODeFMpy20IxSYIa34hBcIcNtO60MBp7nFFsbI0MY4JhFWwlSfBdFw80MqbPWNAk9cNOGBdbGxBDC2Z0vXLcT+O73CiI35n4Y8hhXW4FndBsjBRNDoqOgzSJkGBrVVMsQ57M0Hncqh6/AiiGaUySgAwIERXqqY4juyrQT/HAjf0wxVC1DSBzuLlD0zS64XobrplteBbF+4U0vw23Tra6CL72t0TCE3rLpRldDXztiaG3pqBN9UGA1qyJDEv9tusnV4IOkUj9Ec4q35AK5RG9QRYad64UYSXmGWNpfTbe3KnzwqCJDb9gtM0OnUcsKMuzWWMixUs/2lQznTTfWDurFGqUtbW0I2IyzcrKvYji9da0bMihDiyqGLQ1yFyMsy/CrG7OmPO6Bgo2C4bzVsScjVLZGwXDTVRGq094UDPdNt9Met2KGyNxGTTfTFmwtKjvZz8tw03RLrUGyM3PRjKwMveDedEOtgZzTiZdbxcgxnDbdzlfggyg3JOYYJpanZv82uVKlXvfO9cNPm1MTWo/dHjQ+0GxzXk2WodWiNma4HU6ng7jxFGIwK5Kh1cRp4oNPpuVnxw2ujNxCVJahXTcEPb71Kri5bXBlfBdp6dauIz0jCJa3yBkuRaPFyorh5JmX3HR8YJfNdsswtMyyfPD9ui1w+uZmGdpmAg/lMzSLbIJ0hmFoedoxKy/jeWeHjbWAj5piZGgXRiRJydSWxo5bXB0HM8O9lZL6EzAhehosm86W9sHKzNDytMSp2YSbNqTa7ucmhtgQWjRR9rcbZ5gN1jwZ8lVDQxPJV6tTP46iKF5uLuT9hASudj2CFXZr2es88ObhlfT+Jp0WY88+XwFwHfV6O3LsDl2B1WESJ/7CZ9p+PpTNXegYYoqGSKk/wee6jqNnxA4O+gc+sVjAIAhmAcTTyyF+rYB3Rl968iezweJ7+yTZZ196PriuIT4fAhRzgfuM/279AId1uInDXF6hj89iYGgYLMh+kgsr/0NCBWRTcH8nMgQJBuidtlwHYZgGOsWzNIpoG6YjQvRDXvfmed4DuM0/N+G//liROpkZLuQrQuOCBTrTxqPZYPTStHLEgLZvyM6AGa51C84phpCeCp+D+7ISQ7xszS/EwpsnwRkJIrmcxr0pGP7k1TSTVJuW4cVAT3avZZZU8E8ZqjbPsZaNJYbkI1aMjvYOP83wGZDA2z3QKCBu2xEdvACn43AJQsUSy5eJoW7pl/RBltDBqnDB569uIK2lTIbPgyAjJGQIqez4bcJql5EhwijgFxzKWgIhjpUlh9PlOwGxop7fXssQ/Vqbn8BUlB/Ii1iSl99pGfpchhAKQbODhQwhLyLIhMS82TRDXrcFHbWhcUIKojOr4e8dLMONoh/6eoYe1BFE2Il2pjoZzw6TtVRYBEZRWF9JSyGczgLphCCjpfgtm5OhswS3FY9OwDW94eN4/Jssc0naPsgas/RbgwhTq+RxP1xO2etRjuEppIj5zejT98ldyDBAXe9n9T3lt4lqT1qGPutR+DZ9iEEOjgDdAHL73hxyBElTecsqMMQjOm8KhLMTkyrpmCxELjPkOPPTypm4/DNiXG4eV4nPPENApiyyxmCdOOmk8ER6DpyyNAYtTcRBx5twJLYDrKO+jqEYmOStbxJDdP+FhzXOMSSu0jrVKaBHjY4tQ5MMRZfwZjdJNQ4iUdqSoUjzOecYEozk4CCuqtIr4fhaMCSZHOwmnqSyJhMw4m9sGMq25ZCzNBQnL7Wuq7Kd5RlCA0PhJ0yv+Q0Kaa+tDEPId8SJjEIi0aylwUjt3So3v9YxhCYZjvkxun5gJcMVLeWJxHQk3+Vl6IOblFZZMiCvlyHU98MTZ6hbXazM8NhfRDNxb8cahsCXM/JKRpEM/VBvSxPeFl0B1ooMofQP+sNyynMMkaLepNHtWC4n1ILh5NlYNzIkDp3w6rzpTsMQpDwNWDKv18qWisF7KK0V0lpDvo0tTXl+Yt6dtTQTfGFpxo21uWgfltmn0WvpgV9jKjvzpOasDUNp1hEkPTHAZmRIdTTtBu8LFmHNfql2buGDnpglbMQlSIDNjqGYTyFFHdMdaHmG+MTpmAsrsFIwIurnFob5IfCpTxMgn6YnXWKM5sz0TWVbGvFbFuzVMsSffXpe2qeB3m8hQ/380DTHFzU2EcWR/GHAxF5VS71E0MGrVUotBRPRB9eiVNtsV8QwExIuG6fZS52nf8DX2P0e8V1dW8qwDyCfH56UDP2nPwO93l1MMsxLP/lNUKVjbfL8EB6P0RFbLBGmsWG4EXGYu1qGZzFeJkAcbQ6XkbmxiaEhXroPuJ7wu0lDLWxqZ+O1Rfy6TA8yDFdTLjYcimdLlDi6Z1pIN8VLDTFvn65ayWEXsmbvCVNhxfAiIlYbFcNYSG2Lza0YsIxzxJz9rbJuEXoQyqbNY++nK0uG4IMH3dDkyc9GE0mKGrmbCU8G4k7Q2WhstOsWz5unuznYnsJMGi705iv5tBUYTuhGczy1gPTWyjLc02Ac+vp4Zbd9yvvHTO+f+mCf2VBaaf1w7Hly4IS8+thbzA+ZDHGEkoVfwyzDhccDz2RyjB2Li7DmentauH5oWgNGRO6yBpBqyTimP7FkSFxIrIcB6Wsphme2fkC8beKLoj9Pe37WN/JuZpgYogTkm4M8asS0mDCGiORLPxA5yVJCp3Cp6N6xf+JcWPPEucFIfD6ghf6Ih79/zoZ1OaKF6/gLAIrK0fij0/JjsfzYbMWR0k3JhTdAqpyrfmIwka47Ee+0R2seYANypjTLcH41dsRcA/1cM5SrweWSM9XfSSeUz6g9UXZtL7ueZy6j4KuvKYina9OKN8/ZCHv1PIxP93zmag+Hw2Qn/UIuGS6mhr6BYW9awFDve4tzZ1imGWaOlWbLqa/93Ff4gyt1ROFF8Qt2Gf/5Uo2LV8AwKRFxrQ0ic3JlXxUnV0HCSX6pI+CgLKX4QhnK3AK0kxxhR0iEO3G03j3nzzJBIDd53g5AF5kFReu6MZeCPG/YaP25RGipnQype17QD4Mm91tcPBZGte2HyDwdPbOW4tlQg+n2eNdSIJzt6kDjTY6gYmdXg/ue9mvSQHi2+7nvl9n31HAa8ymO5kkPZ7JVlyH+RSzSI3QMMf7f+w8xbDOhW4CSe0jnLSrcXREl9wF7I3ufqVlkp/dahh0s3UKhfLyXsqZCa4uymnEtW1OhVN5RG3FW5rX+n2qbrHP+jJZh0Uy/nRjl/Rk9w/95jSGMDtaJUvkzWobdq/XlV6z1BQ350G1FpXptuCd+dM2v0YlQX/uyY8UjvmaaPR76ypCN7wWthqVytDfKsFs12zRjoYEh7JhjM/QCVY0oo5Z6nakjPFEsVpRhiDdpNVuqpCwsa0FjPU26IcOCxz5rLY1HRoxOMBzZ1WTHHNtfV59lftoxxBxb/2wEPKmwfzYC6ooBCfG3meFrz7eAAQ6At9qc+rqZfUmGXtvtqU+yMl94zgzGv7YKkSZ2XMwCLMNwYFeT5w0gNQiyuSUWDNv46EMKljD4sgxb+9w1QPdE6Rzu0gwh1O91ahz/iiVYSoZBO8OnZZ5IVpKhlEzfKoyKrUwphmSWcWzhc5Fu+TKXdgxptnqkz+dsCs6eJUtpetGjTSO/n08jfZUh3QDcForun+lMFH6pKAXTFCoQLMeQbpJpUQR1Uc7IlGfIMG/YfxMqVPqZ3NUYwnaYm8mzDKVzhrjqRwseX/1VjWAVLcUUp40XCr4XPx/XmiEhGfw2S3CrXZ9ww5DG34Dvv70/sohfQVzNCUPoxfvURp93EUTXe1QYBi0ZUhWJts+b+jaGCKOoooJaMaTu7vvnxHgHc1BmwvsiQ3GJ+AqkLUJ1s8P68tCkyzhnyDEYg3cFi8nert9pcUTGKUNcoWIH5I1lNTIEYC9tNnkXQ3S96dse7fV51C/T18XQI9sihm9JRL3FXj4Dv36GGLgIA92lW0ePZG7Fw7jAWz9Db7Z54O5YD0MArt/ZMvlvZUg7x3FcjwwxyU9TCsJbGNL+/ywE7Baf81f6nwuGUPyZcifHdzN+YI04RZ73ggl1wlAGDEeUof+Sx8rdpFVICqe4aJkThuROz+LLlXG0pkgzlCaXxcyDLuSH4YIh5NqEt5297Kv2wrkT7eRwpKV80uENw5c64nVD4miQ1y9yAFf9UEIUisTNfFEJkPoqje2mYpCpFNwzJH7Ax/nAgqta0+PLs6/JYfwxtZw8FKAGhqy6UzTcbHuPNCelYva238M5rsvirOulUIOWylZivuifDtpNqY/RuB+veU2zmijWwFCB6Tru95Mw3Jw///1uwjDsI2aKJdw6KL6HYZN4O8N6OpsBb2bobpgrjbcyFPUI33nRv37Yffwx7D7+GHYffwy7j/8/w/8AZEbD4c+xPLsAAAAASUVORK5CYII=
    mediatype: image/png  
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - cic-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - charts.helm.k8s.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - '*'
        serviceAccountName: cic-operator
      deployments:
      - name: cic-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: cic-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: cic-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: cic-operator
                - name: RELATED_IMAGE_CIC
                  value: registry.connect.redhat.com/citrix/citrix-ingress-controller:latest
                - name: RELATED_IMAGE_EXPORTER
                  value: registry.connect.redhat.com/citrix/citrix-adc-metrics-exporter:latest
                image: registry.connect.redhat.com/citrix/citrix-k8s-ingress-controller:latest
                imagePullPolicy: Always
                name: cic-operator
                resources: {}
              serviceAccountName: cic-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ingress controller
  - API Gateway
  - Citrix  
  links:
  - name: Citrix Ingress Controller
    url: https://github.com/citrix/citrix-k8s-ingress-controller
  maintainers:
  - email: NSCPXOrchestration@citrite.net
    name: Citrix
  maturity: alpha
  provider:
    name: Citrix
  version: 1.8.19
